We can import array by this code.

Suppose, we want to import sudoku file which is an array.

In [8]:
import numpy as np

In [9]:
with open('/content/sudoku_solution.npy','rb') as f:
          suduko=np.load(f)
print(suduko)

[[3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]
