## We can import array by this code.

## Suppose, we want to import sudoku file which is an array.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np

In [4]:
with open('/content/drive/MyDrive/DataCamp/Data/NYP/sudoku_solution.npy','rb') as f:
          suduko=np.load(f)
print(suduko)

[[3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]


## Now, we created a list and converted into an array and we will save it as "new an.npy" file name.

In [8]:
a=[3,5,6,4,6,6]
an=np.array(a)
an

array([3, 5, 6, 4, 6, 6])

In [9]:
with open('new an.npy','wb') as f:
    np.save(f,an)